language: python
python:
  - "2.7"
# command to install dependencies
install: "python ./setup.py install"
# command to run tests
script: 
  - genpac --config-from=config.ini
  - ls
# deploy pac file
after_success:
  - bash deploy.sh
